export type ImportIgnoreToken =
	"VApp" |
	"VAppBar" |
	"VAppBarNavIcon" |
	"VAppBarTitle" |
	"VAvatar" |
	"VAlert" |
	"VAlertTitle" |
	"VAutocomplete" |
	"VBadge" |
	"VBanner" |
	"VBannerActions" |
	"VBannerText" |
	"VBreadcrumbs" |
	"VBreadcrumbsItem" |
	"VBreadcrumbsDivider" |
	"VBottomSheet" |
	"VBtnGroup" |
	"VBottomNavigation" |
	"VBtnToggle" |
	"VBtn" |
	"VCard" |
	"VCardActions" |
	"VCardItem" |
	"VCardSubtitle" |
	"VCardText" |
	"VCardTitle" |
	"VCarousel" |
	"VCarouselItem" |
	"VChipGroup" |
	"VCode" |
	"VCheckbox" |
	"VCheckboxBtn" |
	"VCombobox" |
	"VChip" |
	"VDataTable" |
	"VDataTableFooter" |
	"VDataTableRows" |
	"VDataTableRow" |
	"VDataTableVirtual" |
	"VDataTableServer" |
	"VCounter" |
	"VColorPicker" |
	"VDialog" |
	"VDivider" |
	"VDatePicker" |
	"VDatePickerControls" |
	"VDatePickerHeader" |
	"VDatePickerMonth" |
	"VDatePickerMonths" |
	"VDatePickerYears" |
	"VExpansionPanels" |
	"VExpansionPanel" |
	"VExpansionPanelText" |
	"VExpansionPanelTitle" |
	"VFileInput" |
	"VFooter" |
	"VField" |
	"VFieldLabel" |
	"VIcon" |
	"VComponentIcon" |
	"VSvgIcon" |
	"VLigatureIcon" |
	"VClassIcon" |
	"VImg" |
	"VInfiniteScroll" |
	"VLabel" |
	"VKbd" |
	"VInput" |
	"VItemGroup" |
	"VItem" |
	"VMain" |
	"VList" |
	"VListGroup" |
	"VListImg" |
	"VListItem" |
	"VListItemAction" |
	"VListItemMedia" |
	"VListItemSubtitle" |
	"VListItemTitle" |
	"VListSubheader" |
	"VMessages" |
	"VMenu" |
	"VNavigationDrawer" |
	"VOverlay" |
	"VOtpInput" |
	"VPagination" |
	"VProgressCircular" |
	"VProgressLinear" |
	"VRadioGroup" |
	"VSelect" |
	"VSelectionControl" |
	"VRating" |
	"VSkeletonLoader" |
	"VSheet" |
	"VSelectionControlGroup" |
	"VSlideGroup" |
	"VSlideGroupItem" |
	"VSnackbar" |
	"VSwitch" |
	"VSystemBar" |
	"VStepper" |
	"VStepperActions" |
	"VStepperHeader" |
	"VStepperItem" |
	"VStepperWindow" |
	"VStepperWindowItem" |
	"VTabs" |
	"VTab" |
	"VSlider" |
	"VTextarea" |
	"VTable" |
	"VTextField" |
	"VTooltip" |
	"VToolbar" |
	"VToolbarTitle" |
	"VToolbarItems" |
	"VWindow" |
	"VWindowItem" |
	"VTimeline" |
	"VTimelineItem" |
	"VDataIterator" |
	"VDefaultsProvider" |
	"VForm" |
	"VContainer" |
	"VCol" |
	"VRow" |
	"VSpacer" |
	"VHover" |
	"VLazy" |
	"VLayout" |
	"VLayoutItem" |
	"VLocaleProvider" |
	"VNoSsr" |
	"VRadio" |
	"VParallax" |
	"VRangeSlider" |
	"VResponsive" |
	"VThemeProvider" |
	"VValidation" |
	"VVirtualScroll" |
	"VFabTransition" |
	"VDialogBottomTransition" |
	"VDialogTopTransition" |
	"VFadeTransition" |
	"VScaleTransition" |
	"VScrollXTransition" |
	"VScrollXReverseTransition" |
	"VScrollYTransition" |
	"VScrollYReverseTransition" |
	"VSlideXTransition" |
	"VSlideXReverseTransition" |
	"VSlideYTransition" |
	"VSlideYReverseTransition" |
	"VExpandTransition" |
	"VExpandXTransition" |
	"VDialogTransition" |
	"ClickOutside" |
	"Intersect" |
	"Mutate" |
	"Resize" |
	"Ripple" |
	"Scroll" |
	"Touch"